### ISSUE TITLE
Broken since a while -- possible fix from Gentoo

### ISSUE THREAD

**Issue by sphakka** [charleseidsness/alsaequal#1]
It used to work time ago. But now I get:
```
$ alsamixer -D equal
ALSA lib ctl_equal.c:268:(_snd_ctl_equal_open) Problem with control file .alsaequal.bin, 3.
cannot open mixer: Operation not permitted
```
I'm on Gentoo with, `alsaequal-0.6-r2` and `caps-plugins-0.9.15`. Possible fix here: https://bugs.gentoo.org/show_bug.cgi?id=499298

**Comment by charleseidsness** [comment]
This is intended as an archive, I haven't done any development in this in a decade. There are probably better sources for this now.
